In [1]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [21]:
x_data=np.array([[1,0,0,1,0,0,1,0], #0
       [1,0,0,1,0,0,1,1], #1
       [0,1,0,1,0,0,1,0],
                 [0,0,1,0,1,0,1,0],#3
       [0,0,1,0,0,1,0,0],#4
       [0,0,1,0,0,1,0,1],
       [0,1,0,0,0,1,0,1],
       [1,0,0,0,1,0,1,0],
       [1,0,0,0,0,1,0,0],
       [0,0,1,0,1,0,0,0],
       [1,0,0,0,1,0,0,1],
       [0,1,0,0,1,0,1,1],
       [0,1,0,1,0,0,0,0],
       [0,0,1,0,1,0,1,1]])

In [22]:
Y_data = np.array([0,0,1,1,1,0,1,0,1,1,1,1,1,0])

In [23]:
x_data.shape

(14, 8)

In [24]:
Y_data.shape

(14,)

In [29]:
Y_data == True

array([False, False,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True, False])

In [30]:
sum(Y_data==True)

9

In [31]:
len(Y_data)

14

In [32]:
P_Y_True = sum(Y_data==True) / len(Y_data)
P_Y_False = 1 - P_Y_True

P_Y_True,P_Y_False 

(0.6428571428571429, 0.3571428571428571)

In [33]:
ix_Y_True = np.where(Y_data)
ix_Y_False = np.where(Y_data==False)

ix_Y_True, ix_Y_False

((array([ 2,  3,  4,  6,  8,  9, 10, 11, 12], dtype=int64),),
 (array([ 0,  1,  5,  7, 13], dtype=int64),))

In [34]:
p_x_y_true = (x_data[ix_Y_True].sum(axis=0)) / sum(Y_data==True)
p_x_y_false = (x_data[ix_Y_False].sum(axis=0)) / sum(Y_data==False)

p_x_y_true, p_x_y_false 

(array([0.22222222, 0.44444444, 0.33333333, 0.22222222, 0.44444444,
        0.33333333, 0.33333333, 0.33333333]),
 array([0.6, 0. , 0.4, 0.4, 0.4, 0.2, 0.8, 0.6]))

In [36]:
# History_arrears	History_current	History_none	History_paid	CoApplicant_coapplicant	CoApplicant_guarantor	CoApplicant_none	Accommodation_free	Accommodation_own	Accommodation_rent
x_test = [0,0,1,1,0,0,1,1]

p_y_true_test = P_Y_True + p_x_y_true.dot(x_test)
p_y_false_test = P_Y_False + p_x_y_false.dot(x_test)

p_y_true_test , p_y_false_test

# 원래는 로그를 취해주는것이 맞고 아닌경우에는 +가아니라 *임

(1.8650793650793651, 2.5571428571428574)

In [39]:
p_y_true_test < p_y_false_test

False

In [38]:
# History_arrears	History_current	History_none	History_paid	CoApplicant_coapplicant	CoApplicant_guarantor	CoApplicant_none	Accommodation_free	Accommodation_own	Accommodation_rent
x_test = x_test = [0,0,1,1,0,0,1,1]

p_y_true_test = np.log(P_Y_True) + np.log(p_x_y_true.dot(x_test))
p_y_false_test = np.log(P_Y_False) + np.log(p_x_y_false.dot(x_test))

p_y_true_test , p_y_false_test

(-0.24116205681688793, -0.24116205681688807)